"""
raanu.market.exchanges — full US-listed symbols, grouped by exchange
=====================================================================
Backs the "full scan" option: pick an exchange, scan everything listed on
it, rather than the hand-curated 470 in ``universe.py``.

Data comes from ``exchanges.json``, regenerated by
``python -m tools.fetch_exchanges`` from NASDAQ Trader's symbol directory.
It is committed rather than fetched at runtime so a deploy never depends on
a third-party download succeeding, and so a scan never blocks on one.

⚠️ These are **listings, not opportunities.** NYSE Arca is 2,703 ETFs and
17 operating companies; Cboe BZX is much the same. The strategies here are
equity strategies (pullback in an uptrend, stage-2 breakout, leader dip), so
scanning an ETF venue mostly buys download time. The curated universe exists
precisely because a bigger list is a cost, not a free option — downloads are
throttled at ~6.2 tickers/sec per host.
"""

from __future__ import annotations

import json
import logging
from functools import lru_cache
from pathlib import Path

from raanu.market.universe import scannable_universe

log = logging.getLogger("raanu.market.exchanges")

EXCHANGES_FILE = Path(__file__).parent / "exchanges.json"

# The default universe, and the key the dashboard's plain "Scan market"
# button uses. Not an exchange — a hand-picked list that spans several.
CURATED = "curated"


@lru_cache(maxsize=1)
def _data() -> dict:
    with EXCHANGES_FILE.open() as f:
        return json.load(f)


def _exchange_tickers(entry: dict, include_etfs: bool = True) -> list[str]:
    return list(entry["stocks"]) + (list(entry["etfs"]) if include_etfs else [])


def catalog() -> list[dict]:
    """Every selectable universe, for the dashboard's dropdown.

    Curated first — it is the default and by far the most useful; the
    exchange-wide options are the deliberate exception.
    """
    out = [{
        "key": CURATED,
        "label": "Curated list",
        "stocks": len(scannable_universe()),
        "etfs": 0,
        "total": len(scannable_universe()),
    }]
    for key, entry in _data()["exchanges"].items():
        out.append({
            "key": key,
            "label": entry["label"],
            "stocks": len(entry["stocks"]),
            "etfs": len(entry["etfs"]),
            "total": len(entry["stocks"]) + len(entry["etfs"]),
        })
    return out


def keys() -> list[str]:
    return [CURATED, *_data()["exchanges"], "all"]


def tickers_for(universe: str = CURATED, include_etfs: bool = True) -> list[str]:
    """Resolve a universe key to the list of tickers to scan.

    Unknown keys fall back to the curated list rather than raising: a stale
    dashboard asking for an exchange that no longer exists should scan
    something sensible, not 500.
    """
    universe = (universe or CURATED).strip().lower()
    if universe == CURATED:
        return scannable_universe()

    exchanges = _data()["exchanges"]
    if universe == "all":
        seen: dict[str, None] = {}
        for entry in exchanges.values():
            for ticker in _exchange_tickers(entry, include_etfs):
                seen.setdefault(ticker, None)   # dedupe, preserve order
        return list(seen)

    entry = exchanges.get(universe)
    if entry is None:
        log.warning(f"Unknown universe {universe!r} — falling back to the curated list")
        return scannable_universe()
    return _exchange_tickers(entry, include_etfs)


def label_for(universe: str) -> str:
    if universe == CURATED:
        return "Curated list"
    if universe == "all":
        return "All US-listed"
    entry = _data()["exchanges"].get(universe)
    return entry["label"] if entry else universe
