"""
tools/fetch_exchanges.py — regenerate raanu/market/exchanges.json
==================================================================
Pulls the full US-listed symbol directory from NASDAQ Trader, which is the
canonical free source: official, updated every trading day, no API key.

    python -m tools.fetch_exchanges

Yahoo is deliberately NOT the source. It has had no official API since 2017,
and while its undocumented screener endpoint will page through ~80k global
equities, that set is dominated by venues (Frankfurt, OTC, Bombay) that
cannot be traded here — it is not a US-listed list.

Run this occasionally; listings change slowly and the file is committed so a
deploy never depends on a third-party fetch succeeding.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

import httpx

BASE = "https://www.nasdaqtrader.com/dynamic/SymDir/"
OUT = Path(__file__).resolve().parent.parent / "raanu" / "market" / "exchanges.json"

# Exchange codes used in otherlisted.txt's Exchange column.
OTHER_EXCHANGES = {
    "N": ("nyse", "NYSE"),
    "P": ("nyse_arca", "NYSE Arca"),
    "A": ("nyse_american", "NYSE American"),
    "Z": ("cboe_bzx", "Cboe BZX"),
    "V": ("iex", "IEX"),
}


def _fetch(name: str) -> tuple[list[dict], str]:
    resp = httpx.get(BASE + name, timeout=60, follow_redirects=True)
    resp.raise_for_status()
    lines = resp.text.splitlines()
    # Last line is a "File Creation Time: ..." trailer, not a record.
    stamp = lines[-1] if lines and lines[-1].startswith("File Creation Time") else ""
    body = "\n".join(l for l in lines if l and not l.startswith("File Creation Time"))
    return list(csv.DictReader(io.StringIO(body), delimiter="|")), stamp


def _clean(rows: list[dict]) -> list[dict]:
    """Drop test issues — NASDAQ publishes synthetic symbols for exchange
    testing that do not trade and have no price history."""
    return [r for r in rows if (r.get("Test Issue") or "N").strip() != "Y"]


def _symbol(row: dict) -> str:
    # nasdaqlisted uses "Symbol"; otherlisted uses "ACT Symbol".
    return (row.get("Symbol") or row.get("ACT Symbol") or "").strip()


def _usable(symbol: str) -> bool:
    """Symbols the price feed can actually resolve.

    Dots and dollar signs mark preferred shares, warrants, units and class
    suffixes. Alpaca's IEX feed is US-common-stock only and yfinance uses a
    different separator for them, so they would produce nothing but failed
    downloads — and each failed download costs retry time inside its batch.
    """
    return bool(symbol) and symbol.isascii() and not set(symbol) & set(".$ ")


def build() -> dict:
    nasdaq_rows, stamp = _fetch("nasdaqlisted.txt")
    other_rows, _ = _fetch("otherlisted.txt")

    def split(rows: list[dict]) -> dict:
        stocks, etfs = [], []
        for row in rows:
            symbol = _symbol(row)
            if not _usable(symbol):
                continue
            (etfs if (row.get("ETF") or "").strip() == "Y" else stocks).append(symbol)
        return {"stocks": sorted(set(stocks)), "etfs": sorted(set(etfs))}

    exchanges = {"nasdaq": {"label": "Nasdaq", **split(_clean(nasdaq_rows))}}
    cleaned_other = _clean(other_rows)
    for code, (key, label) in OTHER_EXCHANGES.items():
        rows = [r for r in cleaned_other if (r.get("Exchange") or "").strip() == code]
        if rows:
            exchanges[key] = {"label": label, **split(rows)}

    return {
        "_comment": (
            "US-listed symbols grouped by exchange. Generated by "
            "tools/fetch_exchanges.py from NASDAQ Trader's symbol directory; "
            "do not hand-edit. Test issues and symbols containing . or $ "
            "(preferred shares, warrants, units) are excluded — the price "
            "feed cannot resolve them and each one costs retry time."
        ),
        "source": BASE,
        "generated_from": stamp,
        "exchanges": exchanges,
    }


def main() -> None:
    doc = build()
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(f"wrote {OUT.relative_to(OUT.parent.parent.parent)}  ({doc['generated_from']})")
    total = 0
    print(f"\n  {'exchange':<16}{'stocks':>8}{'etfs':>8}{'total':>8}")
    for ex in doc["exchanges"].values():
        n = len(ex["stocks"]) + len(ex["etfs"])
        total += n
        print(f"  {ex['label']:<16}{len(ex['stocks']):>8}{len(ex['etfs']):>8}{n:>8}")
    print(f"  {'ALL':<16}{'':>8}{'':>8}{total:>8}")


if __name__ == "__main__":
    main()
